COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:netty-transport',
    '//lib:floodlightpof',
    '//lib:netty',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
