COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:floodlightpof',
    '//protocols/pof/api:onos-protocols-pof-api',
    '//lib:NETTY',
    '//lib:netty',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
