COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:floodlightpof',
    '//protocols/pof/api:onos-protocols-pof-api',
    '//lib:NETTY',
    '//lib:netty',
    '//lib:netty-transport',
    '//utils/misc:onlab-misc',


]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
